builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    main: ./cmd/semantic-release/
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -extldflags '-static'
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.commitDate={{.CommitDate}}
